# Week 3 Day 3

Today, we'll gain more experience using pandas to read and write datasets.

The main object in pandas is the <i>pandas dataframe</i> which is similar to a spreadsheet or table. Moreover, we can convert the dataframe into whatever format we like.

For example, consider the following table.

| Name | Age | Major |
|------|----:|--------|
| Alice | 20 | Mathematics |
| Bob | 22 | Physics |
| Charlie | 19 | Biology |

If I wanted to convert this into a dataframe, I could do the following:

In [25]:
import pandas as pd

In [26]:
Name = ['Alice', 'Bob', 'Charlie']
Age = [20, 22, 19]
Major = ['Mathematics', 'Physics', 'Biology']

In [27]:
dataframe = pd.DataFrame({
    'Name': Name,
    'Age': Age,
    'Major': Major
})

In [28]:
dataframe

      Name  Age        Major
0    Alice   20  Mathematics
1      Bob   22      Physics
2  Charlie   19      Biology

In [29]:
type(dataframe)

pandas.core.frame.DataFrame

Pandas will automatically store information about the dataframe that we can easily obtain:

In [30]:
dataframe.info() # basic information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Major   3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes

In [31]:
dataframe.describe() # summary statistics

             Age
count   3.000000
mean   20.333333
std     1.527525
min    19.000000
25%    19.500000
50%    20.000000
75%    21.000000
max    22.000000

In [14]:
dataframe.columns

Index(['Name', 'Age', 'Major'], dtype='object')

In [15]:
dataframe.shape

(3, 3)

We can also easily access data from the dataframe as well:

In [16]:
dataframe.head()

      Name  Age        Major
0    Alice   20  Mathematics
1      Bob   22      Physics
2  Charlie   19      Biology

In [17]:
dataframe.head(1)

    Name  Age        Major
0  Alice   20  Mathematics

In [18]:
dataframe.iloc[0]

Name           Alice
Age               20
Major    Mathematics
Name: 0, dtype: object

In [32]:
dataframe.iloc[0:2]

    Name  Age        Major
0  Alice   20  Mathematics
1    Bob   22      Physics

In [33]:
dataframe['Age']

0    20
1    22
2    19
Name: Age, dtype: int64

In [22]:
dataframe[['Age', 'Major']]

   Age        Major
0   20  Mathematics
1   22      Physics
2   19      Biology

We've already had experience reading a file into a notebook, now we will write our own:

In [34]:
dataframe.to_csv("dataframe.csv", index=False)

In [35]:
pd.read_csv("dataframe.csv")

      Name  Age        Major
0    Alice   20  Mathematics
1      Bob   22      Physics
2  Charlie   19      Biology